apiVersion: v1
kind: Service
metadata:
  name: go-web-hello-world-service
spec:
  selector:
    app: go-web-hello-world
  type: NodePort
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 31080
